export const AUTH_SIGNUP_EVENT = "AUTH_SIGNUP_EVENT";
export const AUTH_SIGNUP_EVENT_SUCCESS = "AUTH_SIGNUP_EVENT_SUCCESS";
export const AUTH_SIGNUP_EVENT_FAIL = "AUTH_SIGNUP_EVENT_FAIL";

export const AUTH_AUTHENTICATION_EVENT  = 'AUTH_AUTHENTICATION_EVENT';
export const AUTH_AUTHENTICATION_EVENT_SUCCESS  = 'AUTH_AUTHENTICATION_EVENT_SUCCESS';
export const AUTH_AUTHENTICATION_EVENT_FAIL  = 'AUTH_AUTHENTICATION_EVENT_FAIL';